# fly.toml app configuration file generated for emojit-eiwia6oo on 2025-01-28T21:14:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'emojit-eiwia6oo'
primary_region = 'lhr'

[build]

[deploy]
  strategy = 'immediate'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.ok]
    port = 8000
    type = 'http'
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'
    method = 'get'
    path = '/docs'

[[vm]]
  size = 'shared-cpu-1x'
