# deploy using fly.io
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  python-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - name: Install dev dependencies
        run: uv sync --dev
      - name: Run black
        run: uv run black src/app/
  docker-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
  deploy:
    runs-on: ubuntu-latest
    needs:
      - python-lint
      - docker-lint
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
