# deploy using fly.io
name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - "src/app/**"
      - "Dockerfile"
      - "uv.lock"
      - "pyproject.toml"
      - "fly.toml"
      - ".github/workflows/deploy.yaml"

jobs:
  python-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - name: Install dev dependencies
        run: uv sync --dev
      - name: Run black
        run: uv run black src/app/
  docker-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
  deploy:
    name: Deploy app to Fly.io
    runs-on: ubuntu-latest
    needs:
      - python-lint
      - docker-lint
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
